pipeline {
    agent any
    triggers {
            githubPush()
            echo 'Building elixar-web prod..'
        }
    stages {
        stage('Build') {
            steps {
                echo 'Building elixar-web prod..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing elixar-web prod..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying elixar-web prod....'
            }
        }
    }
}
