node {
    stage('Configuration') {
        properties([pipelineTriggers([[$class: 'GitHubPushTrigger'], pollSCM('H/15 * * * *')])])
        echo 'Deploying elixar-web prod....'
    }
    stage('Preparation') {
            echo 'Deploying elixar-web prod....'
    }
    stage ("Install dependencies") {
            echo 'Deploying elixar-web prod....'
    }
    stage('Build') {
            echo 'Deploying elixar-web prod....'
    }
}
